### ISSUE TITLE
Generalized compilation setup and instructions

### ISSUE THREAD

**Issue by the5thbeatle** [14corman/AIDescisionTree#10]
Compilation should be made simple so that a user can easily build or test various pieces of the project. This includes:
  - An explicit specification of the OCaml version to be used
  - Files generated by a compiler are in the .gitignore
  - Running any given file with a dependency should be explained in the README (e.g. running/testing a file that uses the graph library, testing a file that uses DecisionTree.ml)

**Comment by 14corman** [comment]
If we were making a library then I would say this should all be done, but we are making a class project and there are a few problems here:

1. We only have a week to build and run everything let alone make it "easy" for any user to pick up. We just need to write something up for our report that tells Cesare and Jeff how to build the code (that is if they want to), and how to run it. Running is made easy because make builds an executable for you which is what I have been using to test everything and these are the exe files that are included in the test directory.

2. The files generated by the compiler are required for everyone. That is why I explicitly left them out of the gitignore so you and Jace do not have to waste over 2 days trying to figure out misshapen libraries and a horrible user set up that ocaml has. Merlin uses these files (using the .merlin file) to help with coding in the visual studio ide. This is the reason why I put this as a specific description in the README already.

3. The graph librarie are included in the repository because, again, of all the time I wasted just trying to get it set up. This is way, again, I included that in the README. The only other library used is the Str library which is an included library in ocaml. As for version, we can put down that it is 4.07.1 in the README, but it may be different for each one of us. For instance, I am on a windows laptop so I am running ocaml-variants.4.07.1+mingw64c.

The only thing that could be added to the README is mentioning that testing and running can be done with any exe files that are in the repo. Were you able to read the README on the main repo page? If you have any questions or want to add something go ahead. We will not be making a library here, so I do not think we have to go too in depth. I made our README in depth enough so you and @Neuby121 could get an idea of how to work with the code in case you need to add anything.

**Comment by the5thbeatle** [comment]
The problem is that I’m not able to build anything with the given
instructions so that I can test a file. For starters, make fails because
it’s MAKEFILE instead of Makefile. If I make that change, though, make
terminates when trying to find ocamlgraph.

I know we’re limited on time, but we have to be able to run subunits of the
project.

**Comment by 14corman** [comment]
I think the MAKEFILE problem may be a result of github as I have the Makefile file on my computer from the repository. What is your error you are having that comes up? If it an error about ```module Graph cannot be found ``` then there may be a problem with ocamlgraph not being installed. That is something I was not able to test since I installed the library, but never got it to work. It only started working when I put it, and referenced it, directly in the repository. Once that started working, I never went back and tried to uninstall ocamlgraph to see if it still worked.

Try running ```opam install ocamlgraph``` and then try make. If there is a different error, when you are able to test it, then let me know.

**Comment by 14corman** [comment]
When you get a change, paste your terminal output here so that I can see what the problem is. Here is what running make gives in my terminal:
```
$ make
make[1]: Entering directory '/home/CoryEdwards'
ocamlfind ocamldep -I src/ -I test/ src/DecisionTree.ml > ._d/src/DecisionTree.d
ocamlfind ocamlc -package ocamlgraph,Str -c -I src/ -I test/ src/DecisionTree.ml
ocamlfind ocamlc -package ocamlgraph,Str -c -I src/ -I test/ src/TreeClassifier.ml
ocamlfind ocamlc -package ocamlgraph,Str -c -I src/ -I test/ test/ParseDotTest.ml
ocamlfind ocamlc \
                        -package ocamlgraph,Str -linkpkg \
                             -I src/ -I test/     -ccopt -Lsrc/ -ccopt -Ltest/    ocamlgraph/*.cma -o parseDotTestProgram.exe \
                        src/DecisionTree.cmo src/TreeClassifier.cmo test/ParseDotTest.cmo
make[1]: Leaving directory '/home/CoryEdwards'
```

Again, having the ocamlgraph library installed did not work. Having the library built files in this repository did. However, since this build finds the library, then that should be the first thing that you try and do.

**Comment by the5thbeatle** [comment]
Here's the output for various commands:
```
noah@LAPTOP-4AAGCLDA:~/Documents/courses/AI/AIDescisionTree$ make
make: *** No targets specified and no makefile found.  Stop.
noah@LAPTOP-4AAGCLDA:~/Documents/courses/AI/AIDescisionTree$ mv MAKEFILE
Makefile
noah@LAPTOP-4AAGCLDA:~/Documents/courses/AI/AIDescisionTree$ make
make[1]: Entering directory
'/home/noah/Documents/courses/AI/AIDescisionTree'
ocamlfind ocamlc -package ocamlgraph,Str -c -I src/ -I test/
src/TreeClassifier.ml
ocamlfind: Package `ocamlgraph' not found
OCamlMakefile:1076: recipe for target 'src/TreeClassifier.cmo' failed
make[1]: *** [src/TreeClassifier.cmo] Error 2
make[1]: Leaving directory '/home/noah/Documents/courses/AI/AIDescisionTree'
OCamlMakefile:761: recipe for target 'byte-code' failed
make: *** [byte-code] Error 2
noah@LAPTOP-4AAGCLDA:~/Documents/courses/AI/AIDescisionTree$ opam install
ocamlgraph
[NOTE] Package ocamlgraph is already installed (current version is 1.8.8).
noah@LAPTOP-4AAGCLDA:~/Documents/courses/AI/AIDescisionTree$
```

**Comment by the5thbeatle** [comment]
Here's the output for various commands:

```noah@LAPTOP-4AAGCLDA:~/Documents/courses/AI/AIDescisionTree$ make
make: *** No targets specified and no makefile found.  Stop.
noah@LAPTOP-4AAGCLDA:~/Documents/courses/AI/AIDescisionTree$ mv MAKEFILE
Makefile
noah@LAPTOP-4AAGCLDA:~/Documents/courses/AI/AIDescisionTree$ make
make[1]: Entering directory
'/home/noah/Documents/courses/AI/AIDescisionTree'
ocamlfind ocamlc -package ocamlgraph,Str -c -I src/ -I test/
src/TreeClassifier.ml
ocamlfind: Package `ocamlgraph' not found
OCamlMakefile:1076: recipe for target 'src/TreeClassifier.cmo' failed
make[1]: *** [src/TreeClassifier.cmo] Error 2
make[1]: Leaving directory '/home/noah/Documents/courses/AI/AIDescisionTree'
OCamlMakefile:761: recipe for target 'byte-code' failed
make: *** [byte-code] Error 2
noah@LAPTOP-4AAGCLDA:~/Documents/courses/AI/AIDescisionTree$ opam install
ocamlgraph
[NOTE] Package ocamlgraph is already installed (current version is 1.8.8).
noah@LAPTOP-4AAGCLDA:~/Documents/courses/AI/AIDescisionTree$
```

**Comment by 14corman** [comment]
I am just revamped the README on the main page. Try looking at that to see if you can get it working. More specifically, start at [To build and run code](https://github.com/14corman/AIDescisionTree#to-build-and-run-code). It will tell you where to get started, and will point to how to get the ocamlgraph library working. I just added more detail for the most part, but there was something I forgot to mention about getting the ocamlgraph library that I added to that part. That should fix all your problems. Let me know how it goes.

**Comment by the5thbeatle** [comment]
Two things. First, the make file complains about "Str" until I replace it with "str". Second, can you tell me what version of OCaml you're using? I have 4.07.0, I've already installed ocamlgraph with opam, and I copied the directory into the ocaml folder, and I'm getting this output:

```
noah@LAPTOP-4AAGCLDA:~/Documents/courses/AI/AIDescisionTree$ make
make[1]: Entering directory '/home/noah/Documents/courses/AI/AIDescisionTree'
ocamlfind ocamlc -package ocamlgraph,str -c -I src/ src/DecisionTree.ml
File "src/DecisionTree.ml", line 1:
Error: /usr/lib/ocaml/ocamlgraph/graph.cmi
is not a compiled interface for this version of OCaml.
It seems to be for a newer version of OCaml.
OCamlMakefile:1076: recipe for target 'src/DecisionTree.cmo' failed
make[1]: *** [src/DecisionTree.cmo] Error 2
make[1]: Leaving directory '/home/noah/Documents/courses/AI/AIDescisionTree'
OCamlMakefile:761: recipe for target 'byte-code' failed
make: *** [byte-code] Error 2
noah@LAPTOP-4AAGCLDA:~/Documents/courses/AI/AIDescisionTree$
```

**Comment by 14corman** [comment]
I am running windows ocaml 4.07.01. I am assuming the windows part is why str is Str. I am not sure why you would be getting that error. when you ran opam install, it should have downloaded the correct ocamlgraph library for you to use, and you took that one and put it in the ocaml folder. My only thought would be to look at what switch you are using, and to see if you have multiple versions of ocaml installed. 

It does not seem to point to the ocamlgraph folder within the repository, but just to check you may want to comment out the line ```LIBS = ocamlgraph/*```. Even though the error does not say anything about it, it could be failing because that code is for my windows version. merlin needs that code, but Makefile should not, so if that works then you should be ok.

**Comment by 14corman** [comment]
Were you able to get it working @the5thbeatle, and get the make command to work?

**Comment by the5thbeatle** [comment]
I wasn't able to. The graph library keeps causing problems.
